/* Regenerates assets/js/reports.js from the source reports in data/scans-txt/.
   The text is embedded rather than fetched so the page works when opened straight
   from disk — file:// blocks fetch().

   Run after adding or editing a .txt report:   node tools/build-reports.mjs
   Then add the new study to SCANS in assets/js/data.js and reference it from the
   relevant level's findings. */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(root, 'data', 'scans-txt');
const OUT = join(root, 'assets', 'js', 'reports.js');

const files = readdirSync(SRC).filter(f => f.endsWith('.txt')).sort();

const entries = files.map(f => {
  // Normalise whitespace only — no words are altered.
  const raw = readFileSync(join(SRC, f), 'utf8')
    .replace(/\r\n/g, '\n')
    .split('\n')
    .map(l => l.replace(/[ \t]+$/, ''))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
  return '  ' + JSON.stringify(f) + ': ' + JSON.stringify(raw);
});

const out = `/* GENERATED by tools/build-reports.mjs — do not edit by hand, do not commit.
   Verbatim text of every report in data/scans-txt/, keyed by filename. Embedded
   rather than fetched so the page works when opened directly from disk (file://
   blocks fetch). Whitespace is normalised; no words are altered.

   This file is gitignored: it carries physician names, accession numbers and ICD
   codes that must not reach the public site. app.js loads it opportunistically and
   hides the "full report" expander when it is absent. Assigned onto window (not a
   bare const) precisely so app.js can feature-detect it. */

window.REPORT_TEXT = {
${entries.join(',\n')}
};
`;

writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${files.length} reports to assets/js/reports.js (${(out.length / 1024).toFixed(1)} KB)`);
